version: "3.9"

services:
  db:
    image: mariadb:10.11
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./deploy/db:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

  app:
    build:
      context: ./deploy/app
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "3000:3000"

networks:
  internal:
